submit_order:
  cron: "0 */2 * * *"
  class: "SubmitOrderWorker"

receive_order:
  cron: "0 */2 * * *"
  class: "ReceiveOrderWorker"

retrieve_order:
  cron: "0 */2 * * *"
  class: "RetrieveOrderWorker"
